Thanks to [@sergelovinov](https://github.com/sergelogvinov/ansible-role-debian-boot/blob/7b9bce40091f046050fdc1173f110f2844663dd7/templates/preseed/proxmox.cfg.j2#L190), just creating a /dev/shm directory solved the issue

diff --git a/os-install/templates/post-install.sh.j2 b/os-install/templates/post-install.sh.j2
--- a/os-install/templates/post-install.sh.j2
+++ b/os-install/templates/post-install.sh.j2
@@ -16,8 +16,11 @@ cd "${STAGING_DIR}/bootstrap"
 
 git checkout "$BOOTSTRAP_BRANCH"
 
+mkdir -vp /dev/shm
+
 ansible-playbook -vv -c local site.yml || \
-    ANSIBLE_STATUS="$?" \\
-    echo "ERROR: Ansible run failed with status code $ANSIBLE_STATUS"
+    printf 'ERROR: Ansible run failed with status code %s\n' "$?"
+
+rmdir -v /dev/shm
 
 echo "END POST INSTALL"
