Updated the post-install script, trying to get Ansible to run (#5)
1. Added automation to create [Debian preseed images](https://wiki.debian.org/DebianInstaller/Preseed)
2. Implemented a preseed configuration that
    * Installs the base system with a full-disk LVM volume group
    * Configures the root user but no other user
    * Installs the packages `resolvconf`, `git`, `curl`, and `ansible-core`
    * Configures [Ansible to pull](https://docs.ansible.com/ansible/latest/cli/ansible-pull.html) from [Nippon-Koku](https://github.com/nausicaea/nippon-koku) as a post-install action
3. Implemented an Ansible playbook to fully configure the host at regular intervals without depending on an Ansible controller:
    * Installs the Ansible user
    * Installs the administration user (for manual maintenance)
    * Installs Tailscale and connects to a tailnet
    * Applies basic OS and SSH hardening
    * Installs K3s in with a custom certificate chain and token (this is necessary due to the pull architecture in Ansible)

The same Ansible inventory and playbook apply to all hosts. Selection is performed based on the host name as determined by the Debian preseed configuration. The root password, admin user password, K3s certificate chain, and token are fully configurable and are stored either hashed inside the preseed config, or using Ansible vault. The K3s role currently only supports servers, not agents.

diff --git a/os-install/templates/post-install.sh.j2 b/os-install/templates/post-install.sh.j2
--- a/os-install/templates/post-install.sh.j2
+++ b/os-install/templates/post-install.sh.j2
@@ -1,19 +1,76 @@
 #!/bin/sh
 
-set -ex
+set -e
 
 echo "START POST INSTALL"
 
-apt-get install -y ansible-core git curl
-
+export ANSIBLE_HOME="{{ ansible_home }}"
+ANSIBLE_ETCDIR="/etc/ansible"
+ANSIBLE_CFG="$ANSIBLE_ETCDIR/ansible.cfg"
+ANSIBLE_REQS="$ANSIBLE_ETCDIR/ansible-requirements.yml"
+ANSIBLE_VAULT_PASSWORD="{{ vault_password }}"
+ANSIBLE_VAULT_PW_FILE="$ANSIBLE_HOME/vault_password"
 BOOTSTRAP_REPO="{{ repo }}"
 BOOTSTRAP_BRANCH="{{ branch }}"
-STAGING_DIR=$(mktemp -d)
+BOOTSTRAP_DEST="{{ dest }}"
+GIT_SYSTEM_GITCONFIG="/etc/gitconfig"
+GIT_ALLOWED_SIGNERS_FILE="/etc/git/allowed_signers"
+GIT_AUTHOR_EMAIL="{{ email }}"
+GIT_AUTHOR_SSH_PUB="{{ ssh_pub }}"
 
-git clone "$BOOTSTRAP_REPO" "$STAGING_DIR"
+echo "PI: Stage 1"
+if [ ! -e /dev/shm ]; then
+    mkdir -vp /dev/shm
+fi
 
-cd "${STAGING_DIR}/bootstrap"
+exit_cleanup() {
+    if [ -e /dev/shm ]; then
+        rmdir -v /dev/shm
+    fi
+}
+trap exit_cleanup EXIT
 
-git checkout "$BOOTSTRAP_BRANCH"
+mkdir -vp "$ANSIBLE_ETCDIR" "$ANSIBLE_HOME" $(dirname "$GIT_ALLOWED_SIGNERS_FILE")
 
-ansible-playbook -v -c local site.yml
+cat <<EOF > "$ANSIBLE_CFG"
+[defaults]
+home = $ANSIBLE_HOME
+interpreter_python = auto_silent
+hash_behaviour = merge
+EOF
+
+cat <<EOF > "$ANSIBLE_REQS"
+collections:
+  - name: ansible.posix
+    version: 2.0.0
+  - name: community.crypto
+    version: 2.24.0
+  - name: community.general
+    version: 10.3.0
+  - name: devsec.hardening
+    version: 10.2.0
+  - name: kubernetes.core
+    version: 5.1.0
+EOF
+
+echo "$ANSIBLE_VAULT_PASSWORD" > "$ANSIBLE_VAULT_PW_FILE"
+
+printf '%s namespaces="git" %s\n' "$GIT_AUTHOR_EMAIL" "$GIT_AUTHOR_SSH_PUB" > "$GIT_ALLOWED_SIGNERS_FILE"
+
+cat <<EOF > "$GIT_SYSTEM_GITCONFIG"
+[gpg "ssh"]
+    allowedSignersFile = $GIT_ALLOWED_SIGNERS_FILE
+EOF
+
+echo "PI: Stage 2"
+ansible-galaxy collection install -r "$ANSIBLE_REQS"
+
+echo "PI: Stage 3"
+ansible-pull -U "$BOOTSTRAP_REPO" -C "$BOOTSTRAP_BRANCH" --clean \
+    --verify-commit \
+    -d "$BOOTSTRAP_DEST" -i bootstrap/inventory.yml \
+    --vault-password-file "$ANSIBLE_VAULT_PW_FILE" \
+    bootstrap/playbook.yml \
+    || printf 'ERROR: Ansible run failed with status code %s\n' "$?"
+
+echo "END POST INSTALL"
